# Generated by Django 4.0.5 on 2022-06-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='target_url',
            field=models.URLField(),
        ),
    ]
